### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by fabiocfabini** [CERN-IT-INNOVATION/quantum-gates#26]
I’m the pypi page of the project it states the imports are different depending on if someone pip installs the project or works from source.

However this is not optimal at all. Am better approach would be to simply add the extra `-e` flag and install the project from source like `pip install -e .`. This way the imports are the same and any changes to the source code would be reflected in the developer environment.

**Comment by romanwixinger** [comment]
Hi @fabiocfabini thanks a lot for suggesting this improved way to contribute to the package. I just created a PR, feel free to review it and provide feedback. In case I can help with anything, just let me know. Cheers, Roman
